import { MenuCategory, NavItem, FoodItem } from "@/types";

export const products: FoodItem[] = [
  {
    imageName: "Quiche-Lorraine.png",
    name: "Quiche Lorraine",
    rating: 4.5,
    reviews: 123,
    price: 12,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "français",
    active: true,
  },
  {
    imageName: "Yakitori.png",
    name: "Yakitori",
    rating: 2.5,
    reviews: 123,
    price: 14,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "japonaise",
    active: true,
  },

  {
    imageName: "Palak-Paneer.png",
    name: "Palak Paneer",
    rating: 3,
    reviews: 123,
    price: 6,
    repas: "végétarien",
    repasType: "petit-déjeuner",
    category: "indienne",
    active: false,
  },
  {
    imageName: "Steak-frites.png",
    name: "Steak frites",
    rating: 5,
    reviews: 123,
    price: 4,
    repas: "non-végétarien",
    repasType: "déjeuner",
    category: "français",
    active: true,
  },
  {
    imageName: "Dal-Makhani.png",
    name: "Dal Makhani",
    rating: 1,
    reviews: 123,
    price: 6,
    repas: "végétarien",
    repasType: "petit-déjeuner",
    category: "indienne",
    active: false,
  },
  {
    imageName: "Biryani.png",
    name: "Biryani",
    rating: 3,
    reviews: 123,
    price: 7,
    repas: "non-végétarien",
    repasType: "déjeune",
    category: "indienne",
    active: false,
  },

  {
    imageName: "Pizza.png",
    name: "Pizza",
    rating: 4.5,
    reviews: 123,
    price: 5,
    repas: "végétarien",
    repasType: "déjeune",
    category: "italienne",
    active: true,
  },

  {
    imageName: "Soupe-oignon-gratinée.png",
    name: "Soupe à l'oignon gratinée",
    rating: 4.5,
    reviews: 123,
    price: 5,
    repas: "végétarien",
    repasType: "petit-déjeuner",
    category: "français",
    active: true,
  },

  {
    imageName: "Poulet-au-beurre.png",
    name: "Poulet au beurre",
    rating: 4.5,
    reviews: 123,
    price: 8,
    repas: "non-végétarien",
    repasType: "dîner",
    category: "indienne",
    active: true,
  },

  {
    imageName: "Boeuf-Bourguignon.png",
    name: "Boeuf Bourguignon",
    rating: 4.5,
    reviews: 123,
    price: 10,
    repas: "non-végétarien",
    repasType: "petit-déjeuner",
    category: "français",
    active: true,
  },
  {
    imageName: "Coq-au-vin.png",
    name: "Coq au vin",
    rating: 4.5,
    reviews: 123,
    price: 12,
    repas: "non-végétarien",
    repasType: "déjeuner",
    category: "français",
    active: true,
  },
  {
    imageName: "Lasagna.png",
    name: "Lasagna",
    rating: 4.5,
    reviews: 123,
    price: 14,
    repas: "non-végétarien",
    repasType: "non-végétarien",
    category: "italienne",
    active: false,
  },
  {
    imageName: "Crêpes.png",
    name: "Crêpes",
    rating: 4.5,
    reviews: 123,
    price: 15,
    repas: "non-végétarien",
    repasType: "dîner",
    category: "français",
    active: true,
  },
  {
    imageName: "Ratatouille.png",
    name: "Ratatouille",
    rating: 4.5,
    reviews: 123,
    price: 17,
    repas: "non-végétarien",
    repasType: "dîner",
    category: "français",
    active: true,
  },

  {
    imageName: "Magret-de-Canard.png",
    name: "Magret de Canard",
    rating: 4.5,
    reviews: 123,
    price: 21,
    repas: "non-végétarien",
    repasType: "dînerr",
    category: "français",
    active: true,
  },
  {
    imageName: "Pasta.png",
    name: "Pasta",
    rating: 4.5,
    reviews: 123,
    price: 9,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "italienne",
    active: true,
  },
  {
    imageName: "Salade-Niçoise.png",
    name: "Salade Niçoise",
    rating: 4.5,
    reviews: 123,
    price: 7,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "français",
    active: true,
  },
  {
    imageName: "Blanquette-de-Veau.png",
    name: "Blanquette de Veau",
    rating: 4.5,
    reviews: 123,
    price: 16,
    repas: "végétarien",
    repasType: "dîner",
    category: "français",
    active: true,
  },
  {
    imageName: "Soufflé.png",
    name: "Soufflé",
    rating: 4.5,
    reviews: 123,
    price: 22,
    repas: "déjeuner",
    repasType: "non-végétarien",
    category: "français",
    active: true,
  },
  {
    imageName: "Dropa Khatsa.png",
    name: "Dropa Khatsa",
    rating: 4.5,
    reviews: 123,
    price: 8,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "tibétaine",
    active: true,
  },
  {
    imageName: "Momos.png",
    name: "Momos",
    rating: 4.5,
    reviews: 123,
    price: 8,
    repas: "non-végétarien",
    repasType: "dîner",
    category: "tibétaine",
    active: true,
  },
  {
    imageName: "Thenthuk.png",
    name: "Thenthuk",
    rating: 4.5,
    reviews: 123,
    price: 10,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "tibétaine",
    active: true,
  },
  {
    imageName: "Cassoulet.png",
    name: "Cassoulet",
    rating: 4.5,
    reviews: 123,
    price: 12,
    repas: "végétarien",
    repasType: "déjeuner",
    category: "français",
    active: true,
  },

  {
    imageName: "Bún chả.png",
    name: "Bún chả",
    rating: 4.5,
    reviews: 123,
    price: 20,
    repas: "végétarien",
    repasType: "dîner",
    category: "vietnamienne",
    active: true,
  },
  {
    imageName: "Phở.png",
    name: "Phở",
    rating: 4.5,
    reviews: 123,
    price: 8,
    repas: "non-végétarien",
    repasType: "dîner",
    category: "vietnamienne",
    active: true,
  },
  {
    imageName: "Sushi.png",
    name: "Sushi",
    rating: 4.5,
    reviews: 123,
    price: 22,
    repas: "non-végétarien",
    repasType: "dîner",
    category: "japonaise",
    active: true,
  },
  {
    imageName: "Gỏi-Cuốn.png",
    name: "Gỏi Cuốn",
    rating: 4.5,
    reviews: 123,
    price: 11,
    repas: "non-végétarien",
    repasType: "non-végétarien",
    category: "vietnamienne",
    active: true,
  },
  {
    imageName: "Tempura.png",
    name: "Tempura",
    rating: 4.5,
    reviews: 123,
    price: 21,
    repas: "non-végétarien",
    repasType: "déjeuner",
    category: "japonaise",
    active: true,
  },
];

export type User = {
  id: number;
  name: string;
  company: string;
  role: string;
  verified: boolean;
  status: string;
};

export const users: User[] = [
  {
    id: 1,
    name: "Candice Schiner",
    company: "Dell",
    role: "Frontend Developer",
    verified: false,
    status: "Active",
  },
  {
    id: 2,
    name: "John Doe",
    company: "TechCorp",
    role: "Backend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 3,
    name: "Alice Johnson",
    company: "WebTech",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 4,
    name: "David Smith",
    company: "Innovate Inc.",
    role: "Fullstack Developer",
    verified: false,
    status: "Inactive",
  },
  {
    id: 5,
    name: "Emma Wilson",
    company: "TechGuru",
    role: "Product Manager",
    verified: true,
    status: "Active",
  },
  {
    id: 6,
    name: "James Brown",
    company: "CodeGenius",
    role: "QA Engineer",
    verified: false,
    status: "Active",
  },
  {
    id: 7,
    name: "Laura White",
    company: "SoftWorks",
    role: "UX Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 8,
    name: "Michael Lee",
    company: "DevCraft",
    role: "DevOps Engineer",
    verified: false,
    status: "Active",
  },
  {
    id: 9,
    name: "Olivia Green",
    company: "WebSolutions",
    role: "Frontend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 10,
    name: "Robert Taylor",
    company: "DataTech",
    role: "Data Analyst",
    verified: false,
    status: "Active",
  },
];

export type Employee = {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  gender: string;
  date_of_birth: string; // Consider using a proper date type if possible
  street: string;
  city: string;
  state: string;
  country: string;
  zipcode: string;
  longitude?: number; // Optional field
  latitude?: number; // Optional field
  job: string;
  profile_picture?: string | null; // Profile picture can be a string (URL) or null (if no picture)
};

export const menuCategories: MenuCategory[] = [
  {
    name: "Tout",
    icon: "dashboard",
    shortDescription: "256 menus",
  },
  {
    name: "Petit-déjeuner",
    icon: "breakfast",
    shortDescription: "50 menus",
  },
  {
    name: "Déjeuner",
    icon: "dinner",
    shortDescription: "56 menu",
  },
  {
    name: "Dîner",
    icon: "lunch",
    shortDescription: "60 menus",
  },
];

export const navItems: NavItem[] = [
  {
    title: "Home",
    href: "/",
    icon: "dashboard",
    label: "Home",
  },
  {
    title: "Order",
    href: "/orders",
    icon: "billing",
    label: "Home",
  },
  {
    title: "Profile",
    href: "/profile",
    icon: "profile",
    label: "profile",
  },
  {
    title: "Settings",
    href: "/settings",
    icon: "settings",
    label: "settings",
  },
  // {
  //   title: "Login",
  //   href: "/",
  //   icon: "login",
  //   label: "login",
  // },
];
