import type { Metadata } from "next";
import Providers from "@/components/layout/providers";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Cloud kitchen using Nextjs shadcn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload the CSS file */}
        <link
          rel="preload"
          href="/_next/static/css/app/(app)/layout.css"
          as="style"
        />
      </head>
      <body>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
