import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import AppProviders from "./providers/AppProviders";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cloud kitchen using Nextjs shadcn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <AppProviders>{children}</AppProviders>
        <Toaster />
      </body>
    </html>
  );
}
