import type { Metadata } from "next";
import Providers from "@/components/layout/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cloud kitchen using Nextjs shadcn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
